#
# Makefile for misc devices that really don't fit anywhere else.
#
                                                                       
ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc

obj-y += nt35532_fhd_dsi_vdo_hp_5516.o




