#
# Makefile for misc devices that really don't fit anywhere else.
#
                                                                       
ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc

obj-y += vm5296_hd720_dsi_vdo_hx.o




