#
# Makefile for misc devices that really don't fit anywhere else.
#
                                                                       
ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc

obj-y += otm1287a_hd720_dsi_vdo_tm.o




