
#obj-$(CONFIG_MTK_BASE_POWER) += base/

obj-$(CONFIG_MTK_GOODIX_FINGER) += gfx1xm/
obj-$(CONFIG_MTK_SUNWAVE_FINGER) += sw9362n/
obj-$(CONFIG_MTK_ICN_FINGER) += icnfpsensor/
obj-$(CONFIG_MTK_FEGE_FINGER) += fegefpsensor/