#include "platform/partition.h"


struct part_name_map g_part_name_map[PART_MAX_COUNT] = {
        {"preloader",   "preloader",    "raw data",     0,      0,      0},
        {"proinfo",     "proinfo",      "raw data",     1,      0,      0},
        {"nvram",       "nvram",        "raw data",     2,      0,      0},
        {"protect1",    "protect1",     "ext4",         3,      0,      0},
        {"protect2",    "protect2",     "ext4",         4,      0,      0},
        {"lk",          "lk",           "raw data",     5,      1,      1},
        {"para",        "para",         "raw data",     6,      0,      0},
        {"boot",        "boot",         "raw data",     7,      1,      1},
        {"recovery",    "recovery",     "raw data",     8,      1,      1},
        {"logo",        "logo",         "raw data",     9,      0,      0},
        {"expdb",       "expdb",        "raw data",     10,     0,      0},
        {"seccfg",      "seccfg",       "raw data",     11,     0,      0},
        {"oemkeystore", "oemkeystore",  "raw data",     12,     0,      0},
        {"secro",       "secro",        "raw data",     13,     0,      0},
        {"keystore",    "keystore",     "raw data",     14,     1,      1},
        {"tee1",        "tee1",         "raw data",     15,     0,      0},
        {"tee2",        "tee2",         "raw data",     16,     0,      0},
        {"persist",     "persist",      "ext4",         17,     0,      0},
        {"custom",      "custom",       "ext4",         18,     0,      0},
	{"recovery2",	"recovery2",	"ext4",        	19,	0,	0},
	{"radio",	"radio",	"ext4", 	20,	0,	0},
	{"vendor",	"vendor",	"ext4", 	21,	0,	0},
	{"odm", 	"odm",  	"ext4", 	22,	0,	0},
	{"oem", 	"oem",  	"ext4", 	23,	0,	0},
        {"efuse",       "efuse",        "raw data",     24,     0,      0},
        {"frp",         "frp",          "raw data",     25,     0,      0},
        {"nvdata",      "nvdata",       "ext4",         26,     0,      0},
        {"metadata",    "metadata",     "raw data",     27,     0,      0},
        {"system",      "system",       "ext4",         28,     1,      1},
        {"cache",       "cache",        "ext4",         29,     1,      1},
        {"userdata",    "userdata",     "ext4",         30,     1,      1},
        {"intsd",       "intsd",        "fat",          31,     0,      0},
        {"otp",         "otp",          "raw data",     32,     0,      0},
        {"flashinfo",   "flashinfo",    "raw data",     33,     0,      0},
        {""},
};
